# this sets the logger level (true = info, false = debug)
production: true

operator_address: 0x860B6912C2d0337ef05bbC89b0C2CB6CbAEAB4A5

# EigenLayer Slasher contract address

# This is the address of the slasher which is deployed in the anvil saved state
# TODO: automate updating these addresses when we deploy new contracts
avs_registry_coordinator_address: 0x9E545E3C0baAB3E08CdfD552C960A1050f373042
operator_state_retriever_address: 0x4c5859f0F772848b2D91F1D83E2Fe57935348029

# ETH RPC URL
eth_rpc_url: http://localhost:8545

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/ecdsa_key.json as the host path will be asked while running
#
# If you are running locally using go run main.go, this should be full path to your local ecdsa key file
ecdsa_private_key_store_path: tests/keys/test.ecdsa.key.json

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/bls_key.json as the host path will be asked while running
#
# We are using bn254 curve for bls keys
#
# If you are running locally using go run main.go, this should be full path to your local bls key file
bls_private_key_store_path: tests/keys/test.bls.key.json

aggregator_server_ip_port_address: localhost:8090

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_metrics_ip_port_address: localhost:9090
enable_metrics: true
node_api_ip_port_address: localhost:9010
enable_node_api: true

register_operator_on_startup: true
# address of token to deposit tokens into when registering on startup
token_strategy_addr: 0x4A679253410272dd5232B3Ff7cF5dbB88f295319
